### ISSUE TITLE
Segfault on 64-bit machines

### ISSUE THREAD

**Issue by sambowne** [ajakubek/python-sha3#1] opened 2015-12-01 22:25 UTC
I tried it on 64-bit Kali Linux 2.0 and on Mac OS X.  It crashes in both cases.  Details are here:

https://samsclass.info/120/proj/sha3crash.htm

**Comment by ajakubek** [comment] 2015-12-02 01:24
Confirmed, there has been a bug in the sha*.update() function. It somehow managed to pass my tests three years ago (probably due to different compiler version).

I've just pushed a fix for the issue.

**Closed as completed by ajakubek** 2015-12-02 01:24 UTC
